import type { ThemeSettings } from "@/config/theme";

/**
 * Preset themes (Phase 8.5) - 4 curated palettes selectable from
 * /admin/theme-settings. Each preset maps onto the ThemeSettings shape;
 * applying one fills the color fields of the settings form and is then
 * persisted like any other theme change.
 */

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  theme: Partial<ThemeSettings>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "cosmic-royal",
    name: "Cosmic Royal",
    description:
      "The signature look: deep royal purple, indigo and bright gold accents.",
    theme: {
      primary: "#4C1D95",
      secondary: "#312E81",
      accent: "#FACC15",
      accent2: "#D4AF37",
      accent3: "#F97316",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#0F172A",
      pageBackground: "#0F172A",
      primaryTextColor: "#0F172A",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#4C1D95",
      cardBackground: "#FFF7ED",
      cardBorder: "#D4AF37",
      heroGradientStart: "#0F172A",
      heroGradientEnd: "#4C1D95",
      topbarGradientStart: "#0F172A",
      topbarGradientEnd: "#4C1D95",
      footerGradientStart: "#111827",
      footerGradientEnd: "#312E81",
      goldGradientStart: "#FACC15",
      goldGradientEnd: "#F97316",
      legalTitleColor: "#4C1D95",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#4C1D95",
      contactFormSurface: "#1E1B4B",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#FACC15",
      experienceBannerTextColor: "#111827",
      experienceBannerBorder: "#D4AF37",
    },
  },
  {
    id: "golden-sunrise",
    name: "Golden Sunrise",
    description:
      "Warm maroon, deep indigo night and bright butter-yellow gold tones.",
    theme: {
      primary: "#800000",
      secondary: "#1E1B4B",
      accent: "#FDE047",
      accent2: "#D4AF37",
      accent3: "#F97316",
      whatsapp: "#25D366",
      emerald: "#16A34A",
      deepNavy: "#1E1B4B",
      pageBackground: "#1E1B4B",
      primaryTextColor: "#1E1B4B",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#800000",
      cardBackground: "#FFFBEB",
      cardBorder: "#D4AF37",
      heroGradientStart: "#1E1B4B",
      heroGradientEnd: "#800000",
      topbarGradientStart: "#1E1B4B",
      topbarGradientEnd: "#800000",
      footerGradientStart: "#111827",
      footerGradientEnd: "#1E1B4B",
      goldGradientStart: "#FDE047",
      goldGradientEnd: "#F97316",
      legalTitleColor: "#800000",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#800000",
      contactFormSurface: "#1E1B4B",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#FDE047",
      experienceBannerTextColor: "#800000",
      experienceBannerBorder: "#D4AF37",
    },
  },
  {
    id: "vibrant-celestial",
    name: "Vibrant Celestial",
    description:
      "Bright electric violet, teal and amber - a modern cosmic energy.",
    theme: {
      primary: "#7C3AED",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      accent2: "#FBBF24",
      accent3: "#EF4444",
      whatsapp: "#25D366",
      emerald: "#14B8A6",
      deepNavy: "#0F172A",
      pageBackground: "#0F172A",
      primaryTextColor: "#0F172A",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#7C3AED",
      cardBackground: "#FFF7ED",
      cardBorder: "#FBBF24",
      heroGradientStart: "#0F172A",
      heroGradientEnd: "#7C3AED",
      topbarGradientStart: "#0F172A",
      topbarGradientEnd: "#14B8A6",
      footerGradientStart: "#111827",
      footerGradientEnd: "#14B8A6",
      goldGradientStart: "#F59E0B",
      goldGradientEnd: "#EF4444",
      legalTitleColor: "#7C3AED",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#FBBF24",
      legalTextColor: "#111827",
      legalHeadingColor: "#7C3AED",
      contactFormSurface: "#111827",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#F59E0B",
      experienceBannerTextColor: "#111827",
      experienceBannerBorder: "#FBBF24",
    },
  },
  {
    id: "deep-space-luxe",
    name: "Deep Space Luxe",
    description:
      "Premium high-contrast: rich purple, midnight navy, champagne gold and emerald.",
    theme: {
      primary: "#4C1D95",
      secondary: "#1E1B4B",
      accent: "#D4AF37",
      accent2: "#EAB308",
      accent3: "#B45309",
      whatsapp: "#10B981",
      emerald: "#10B981",
      deepNavy: "#0F172A",
      pageBackground: "#0F172A",
      primaryTextColor: "#0F172A",
      secondaryTextColor: "#64748B",
      ctaPrimary: "#4C1D95",
      cardBackground: "#FFF7ED",
      cardBorder: "#D4AF37",
      heroGradientStart: "#0F172A",
      heroGradientEnd: "#4C1D95",
      topbarGradientStart: "#0F172A",
      topbarGradientEnd: "#4C1D95",
      footerGradientStart: "#111827",
      footerGradientEnd: "#1E1B4B",
      goldGradientStart: "#D4AF37",
      goldGradientEnd: "#B45309",
      legalTitleColor: "#4C1D95",
      legalBreadcrumbColor: "#111827",
      legalCardBackground: "#FFFFFF",
      legalCardBorder: "#D4AF37",
      legalTextColor: "#111827",
      legalHeadingColor: "#4C1D95",
      contactFormSurface: "#1E1B4B",
      contactFormLabelColor: "#FFFFFF",
      experienceBannerBackground: "#D4AF37",
      experienceBannerTextColor: "#111827",
      experienceBannerBorder: "#B45309",
    },
  },
];

export function themePresetById(id: string | null | undefined): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}
